### PR TITLE
Move to src directory

### PR DESCRIPTION
**Pull request by SatjaSivcev**

### CODE REVIEW

**Comment by SatjaSivcev** [comment]
I will need help understanding where CI fails:
Error copying file "/host/Zivid3D.zdf" to "/host/build/ci/clang/.".

**Comment by knatten** [comment]
A few things (this should already be covered in https://github.com/zivid/cpp-extra-samples/issues/48#issuecomment-578771693):
- You now have two copies of `CMakeLists.txt`. Delete the one in the root folder.
- Undo the changes you did to the `CMakeLists.txt` in the `source` folder, it shouldn't need to change at all.
- Move the `cmake` folder inside the `source` folder.
- Fix the build path in `build.sh` as described in that comment

If that doesn't work, make sure you have CI working locally on your machine and I can come over and help.

**Comment by torbsorb** [comment]
Looks like you've moved all the files to /source/. The links in the README.md seems to have been updated to /src/. Is that going to work? I'm also concerned about the links in the HandEye README.md

**Comment by SatjaSivcev** [comment]
Thanks for the input. I think it should be ok now.

**Comment by SatjaSivcev** [comment]
Ready for review.

**Comment by knatten** [comment]
Looks good now! Please squash into one commit with a proper commit message, and I'll approve. Make sure to mention issue #48 in the commit message. (If you just type `#48` in the commit message, GitHub will automatically link it to the issue.)

**Comment by SatjaSivcev** [comment]
Done. Ready for the final commit message check.

**Pull request merged**
