### PR TITLE
Update license

### PR DESCRIPTION
**Pull request by SatjaSivcev**
I've taken the string from Zivid.h.
I've only changed support@zivid.com to customersuccess@zivid.com.
Should we remove the first sentence related to Zivid API?

### CODE REVIEW

**Comment by SatjaSivcev** [comment]
@nedrebo can you check this?

**Comment by SatjaSivcev** [comment]
@nedrebo reminder for license review

**Comment by nedrebo** [comment]
Why do you think new license is required?

Have you seen this: https://github.com/zivid/zivid-licenses

That is the only place to fetch licenses from.

**Comment by SatjaSivcev** [comment]
> 
> 
> Why do you think new license is required?
> 
> Have you seen this: https://github.com/zivid/zivid-licenses
> 
> Licensing is also covered here: https://github.com/zivid/zivid-repository-guidelines
> 
> That is the only place to fetch licenses from. It is important to copy the licenses verbatim, do not modify or add anything to the LICENSE file.

It was required because it stated 2019. I know what to do know.

**Pull request merged**
