### PR TITLE
1.6 update readme and CMakelists

### PR DESCRIPTION
**Pull request by chrisasc**
small updates on readme and CMake since the Qt dependecies are removed. Issue: ZIVID-2158

### CODE REVIEW

**Comment by knatten** [comment]
Did you see #28? I think we should close this PR and merge #28 instead.

**Comment by SatjaSivcev** [comment]
28 fails to compile Anders. What should we do about it? It should be ready for merge on Monday.

**Comment by knatten** [comment]
@SatjaSivcev it says in my [comment](https://github.com/zivid/cpp-extra-samples/pull/28#issuecomment-545472437) in the PR:
> Note that this PR will stay red until we use 1.6 in CI. I'll rebase it on master as soon as we use 1.6 for CI on master.

**Comment by knatten** [comment]
Bump

**Comment by knatten** [comment]
Agreed with @SatjaSivcev to close this in favour of #28

**Pull request closed without merging**
